/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qusbxzupbfsshnaxqcgb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1c2J4enVwYmZzc2huYXhxY2diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjU5MjQsImV4cCI6MjA3MDQwMTkyNH0.73m4cd_B9lDBHK7o-mekVf9E3tU_vHdzG4l-P-GLhOY"